### ISSUE TITLE
About discussion

### ISSUE THREAD

**Issue by HobbitQia** [gemelom/rl_epiphany#1]
Hi, I'm glad to know that you borrowed from my homepage when building your homepage. However, when you change settings of the homepage, you should also change the setting of giscus, which is for comment function, otherwise comments for your pages will be leaved in my repository, as you can see [this](https://github.com/HobbitQia/notebook/discussions/46).

In `overide/main.html:12-27`, you should configure it by yourself, including data-repo-id, data-category-id, rather than copy mine while only changes the repo name. Tutorials about giscus can be found online.

**Comment by gemelom** [comment]
Fixed in [bf391da](https://github.com/gemelom/rl_epiphany/commit/bf391da94d70aa4dfbd39f0b6a8eb998a920e0e9), and I apologize for the inconvenience caused. You can delete the discussions that were mistakenly send to your repository.

**Comment by gemelom** [comment]
@HobbitQia Fixed in [bf391da](https://github.com/gemelom/rl_epiphany/commit/bf391da94d70aa4dfbd39f0b6a8eb998a920e0e9), and I apologize for the inconvenience caused. You can delete the discussions that were mistakenly send to your repository.

**Comment by HobbitQia** [comment]
> @HobbitQia Fixed in [bf391da](https://github.com/gemelom/rl_epiphany/commit/bf391da94d70aa4dfbd39f0b6a8eb998a920e0e9), and I apologize for the inconvenience caused. You can delete the discussions that were mistakenly send to your repository.

Ok, thanks.
